name: ColconTest

on:
  push:
    branches:
      - 'main'
    paths:
      - 'deployment_utils/lunabot.Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push test
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:deployment_utils"
          push: true
          tags: manglemix/usr_docker_repo:lunabot_test

      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}
        
      - name: Build and push final
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:deployment_utils"
          push: true
          tags: manglemix/usr_docker_repo:lunabot
