name: ColconTest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: osrf/ros:foxy-desktop
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: "bash ./opt/ros/foxy/setup.sh && colcon build && colcon test"
