name: ColconTest

on: [push]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
      - uses: ros-tooling/setup-ros@v0.4
        with:
          required-ros-distributions: foxy
      - run: "source /opt/ros/foxy/setup.bash && colcon test"
