name: ColconTest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: osrf/ros:foxy-desktop
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: "exec bash && source /opt/ros/foxy/setup.bash && colcon build --symlink-install > out.txt && exec sh cat out.txt"

      - name: Test
        run: "exec bash && source /opt/ros/foxy/setup.bash && colcon test --return-code-on-test-failure --event-handlers console_cohesion+ > out.txt && exec sh cat out.txt"
