name: ColconTest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: osrf/ros:foxy-desktop
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: "exec bash && source /opt/ros/foxy/setup.bash"

      - name: Build
        run: "colcon build --symlink-install"

      - name: Test
        run: "colcon test --return-code-on-test-failure --event-handlers console_cohesion+"
