name: ColconTest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: osrf/ros:foxy-desktop
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: "./opt/ros/foxy/setup.sh && colcon test"
