<<<<<<< HEAD
name: ColconTest

on: [push]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
    steps:
      - uses: ros-tooling/setup-ros@v0.4.1
        with:
          required-ros-distributions: foxy
      - run: "source /opt/ros/foxy/setup.bash && colcon test"
      - run: "source /opt/ros/noetic/setup.bash && rosnode --help"

=======
- name: Setup ROS environment
  uses: ros-tooling/setup-ros@0.4.1
>>>>>>> main
