name: ColconTest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: osrf/ros:foxy-desktop
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: "chmod +x /opt/ros/foxy/setup.sh && ./opt/ros/foxy/setup.sh && colcon test"
