name: ColconTest

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - ".github/workflows/colcon_test.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    container: manglemix/usr_docker_repo:usr_base
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        shell: bash
        run: "shopt -s expand_aliases && source /root/.bashrc && colcbuild"

      - name: Test
        shell: bash
        run: "shopt -s expand_aliases && source /root/.bashrc && colctest"
