name: ColconTest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: osrf/ros:foxy-desktop
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug1
        run: "ls /opt"

      - name: Debug2
        run: "ls /opt/ros"

      - name: Debug3
        run: "ls /opt/ros/foxy"

      - name: Test
        run: "chmod +x /opt/ros/foxy/setup.sh && ./opt/ros/foxy/setup.sh && colcon build && colcon test"
