name: ColconTest

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: manglemix/usr_docker_repo:usr_base
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: "bash -c 'colcbuild'"

      - name: Test
        run: "bash -c 'colctest'"
